### ISSUE TITLE
`dbt-helper open` broke for dbt v0.15.0

### ISSUE THREAD

**Issue by bastienboutonnet** [mikekaminsky/dbt-helper#25]
I migrated to `dbt 0.15.0` and when i tried using `dbt-helper open <model_name` it's complaining that the `dbt.loader` module cannot be found.

I checked in the dbt code and indeed the module isn't here.

I don't know when/if I'll have time to look into this so I thought I'd pop an issue here so that it doesn't go missing.

There might be a case here to pin dbt requirements to a version < 15 at setup or so. If I can look into it I'll for sure contribute.

**Comment by mikekaminsky** [comment]
100% an incompatibility with dbt 0.15.0. I will pin the requirements at
<0.15.0 and update the readme.

Unfortunately I’m not currently using dbt for any of my projects so can’t
make upgrading a super high priority. Would definitely merge a PR /
collaborate if you want to take the lead, though!

Thanks for posting the issue!

**Comment by bastienboutonnet** [comment]
Yeah I totally understand. I'll see if I can find some time over the weekend or coming holidays to fix this. My team uses `dbt-helper` quite a bit so if we can help we will!

**Comment by mikekaminsky** [comment]
@bastienboutonnet awesome! I will commit to answering any questions y'all have, helping with development environment, etc. Would love to empower more people to contribute to this project since I'm not actively working on it. Just let me know how I can help -- you can ping me in the dbt slack as well :)

**Comment by bastienboutonnet** [comment]
Sure! I'll see what I can do. It looks like it leverages a lot of the dbt core internals so I'm gonna have to understand their current code. It's been a while and lots has changed. I'll let you know if I need any help regarding stuff that's under your jurisdiction.

**Comment by mikekaminsky** [comment]
See note here: https://github.com/mikekaminsky/dbt-helper/pull/27

I've pinned the repo at `0.14.0` because that's the last dbt version with all functionality working.
