### ISSUE TITLE
Rename subcommands to consistently use `-` instead of `_`

### ISSUE THREAD

**Issue by aescay** [mikekaminsky/dbt-helper#29]
Using dashes `-` vs underscores `_` should keep things consistent and easy to type while hacking away. Should be a very quick fix that I'm happy to do. (likely later today 😅 )

**Comment by mikekaminsky** [comment]
I'm 1000% for this :)

**Comment by mikekaminsky** [comment]
Note: we should start with adding the new functions, and then adding a soft deprecation warning to the old versions. Then we can switch to hard deprecation and error in a future release.
