### ISSUE TITLE
[BUG] Stop dbt-helper from force-installing the latest dbt version

### ISSUE THREAD

**Issue by aescay** [mikekaminsky/dbt-helper#31]
Right now we have it configured to run with dbt 0.17.1 and above, but it shouldn't automatically upgrade you because that might cause issues with your development workflow.

## Steps to replicate
1. run `pip install dbt-helper`.
2. observe that it will install/upgrade your dbt to the latest released version (currently 0.17.2)

## Expected behavior
- Fail when dbt is out of the allowed version (not >= 0.17.1)
- Do not install dbt, instead check that it's installed, maybe prompt you to install if it's not

**Comment by aescay** [comment]
@mikekaminsky spending a bit of time researching this, I don't see a supported solution using the `setup.py` script. I'm thinking of implementing a similar solution to how dbt handles [require-dbt-version](https://docs.getdbt.com/reference/project-configs/require-dbt-version) where dbt-helper checks at runtime instead of during install. Let me know if this sounds good or if you have another idea!

**Comment by mikekaminsky** [comment]
I think that makes sense -- so in `setup.py` we could do `install_requires=["dbt>=0.0.1"],` and then at run time check for which dbt version is installed and error if it's not supported.
