### ISSUE TITLE
Build compatibility for 0.18.0

### ISSUE THREAD

**Issue by aescay** [mikekaminsky/dbt-helper#38]
Tested with the 0.18.0rc1 and dbt-helper is failing all over again. Doesn't look as crazy as the last one, but not sure yet what is breaking.

This is the error message I'm getting
```AssertionError: Cannot track deprecation warnings when active user is None```

**Comment by mikekaminsky** [comment]
Using `dbt==0.18.0rc1` I'm not seeing that error (running the tests via docker & tox)

How'd you generate that error?

**Comment by mikekaminsky** [comment]
This appears to have either been a flaky error or unrelated to dbt-helper. Closing for now!

**Comment by camfrout** [comment]
I had the same error at first, and it also disappeared for me when I updated `dbt==0.18.0rc1`with the latest changes. 
It has been fixed on the dbt side on Aug 22 in this commit: https://github.com/fishtown-analytics/dbt/commit/685873ab426c28f15b795a404f300386d852b7a4
